name: 'ci'

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.7.0]

    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn

  build-client:
    runs-on: ubuntu-latest
    needs: dependencies

    strategy:
      matrix:
        node-version: [13.7.0]

    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn build:client

  build-server:
    runs-on: ubuntu-latest
    needs: dependencies

    strategy:
      matrix:
        node-version: [13.7.0]

    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn build:server